apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: studentski-uspehi
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: studentski-uspehi
    newName: rg.fr-par.scw.cloud/djnd/studentski-uspehi
    newTag: '4386821217b6cf2585f3c1dcd6a60a316f95d911'
